plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.mod_group

base {
    archivesName = project.mod_id
}

repositories {
    mavenCentral()

    maven {
        url = "https://maven.fabricmc.net/"
    }
}

dependencies {
    // Minecraft 26.2 is unobfuscated.
    // DO NOT add Yarn mappings.
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    // Fabric Loader
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand(
            "version": project.version,
            "minecraft_version": project.minecraft_version,
            "loader_version": project.loader_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.mod_id}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
        // Add publishing repositories here if needed.
    }
}
