# Minecraft version
minecraft_version=26.2

# Fabric Loader version
loader_version=0.18.4

# Yarn mappings version
yarn_mappings=26.2+build.1

# Fabric Loom version
loom_version=1.15-SNAPSHOT

# Java version
java_version=25

# Mod properties
mod_version=1.0.0
mod_group=com.example
mod_id=staffradar

fabric_api_version=0.145.0+26.2
