# Minecraft version
minecraft_version=26.2

# Fabric Loader version
loader_version=0.19.3

# Fabric Loom version
loom_version=1.17

# Fabric API version
fabric_version=0.156.0+26.2

# Java version
java_version=25

# Mod properties
mod_version=1.0.0
mod_group=com.example
mod_id=staffradar

# Archive name
archives_base_name=staffradar
